# Tensors
At its core, a tensor is a container for data - usually numerical data. Matrices are rank-2 tensors: tensors are a generalization of matrices to an arbitrary number of *dimensions* (in the context of tensors, a dimension is often called an **axis**)

### Scalars (rank-0 tensors)

In [1]:
import numpy as np
x = np.array(12)
x

array(12)

In [2]:
x.ndim

0

### Vectors (rank-1 tensors)
In this case a *4-dimensional vector*. 4D vector != 4D tensor

In [3]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
x.ndim

1

### Matrices (rank-2 tensors)

In [5]:
x = np.array([[1,2,3],[2,4,6]])
x

array([[1, 2, 3],
       [2, 4, 6]])

In [6]:
x.ndim

2

### Rank-3 and higher-rank tensors

In [7]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [8]:
x.ndim

3

## Key attributes
A tensor is defined by three key attributes:
- *Number of axes (rank)*
- *Shape* - This is a tuple of integers that describes how many dimensions the tensor has along each axis (e.g. the rank-3 tensor has shape (3, 3, 5)). 
- *Data type* - this is the type of the data contained in the tensor (float16, float32, float64, uint8, string, ...)

In [9]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

2021-09-21 09:48:46.832234: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


11493376/11490434 [==============================] - 1s 0us/step

In [10]:
my_slice = train_images[10:100,:,:]
my_slice.shape

(90, 28, 28)

## Real-world examples of data tensors
- *Vector data* - rank-2 tensors of shape (samples, features)
- *Timeseries data or sequence data* - rank-3 tensors of shape (samples, timesteps, features)
- *Images* - rank-4 tensors of shape (samples, height, width, channels) or (samples, channels, height, width)
- *Video* - rank-5 tensors of shape (samples, frames, height, width, channels)

![](imgs/imagedata.png)

## tensor operations